"""Compile project sources without importing scripts or starting experiments."""

import argparse
import ast
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED = {
    ".git",
    ".venv",
    ".codex-tools",
    "__pycache__",
    "results",
    "tmp",
    "plots",
    "plots_result",
    ".pytest_cache",
    ".ruff_cache",
}
LOCAL_PACKAGES = {"agents", "envs", "training", "evaluation", "utils", "scripts", "tools"}


def inspect_sources(root=ROOT):
    """Return an AST-based inventory; imports are references, not proof of runtime use."""
    records = []
    for parent, directories, files in os.walk(root):
        directories[:] = sorted(name for name in directories if name not in EXCLUDED)
        for filename in sorted(files):
            if not filename.endswith(".py"):
                continue
            path = Path(parent) / filename
            source = path.read_text(encoding="utf-8-sig")
            tree = ast.parse(source, filename=str(path), feature_version=(3, 10))
            compile(tree, str(path), "exec")
            imports = set()
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    imports.update(
                        alias.name
                        for alias in node.names
                        if alias.name.split(".")[0] in LOCAL_PACKAGES
                    )
                elif isinstance(node, ast.ImportFrom):
                    if node.level:
                        imports.add("." * node.level + (node.module or ""))
                    elif node.module and node.module.split(".")[0] in LOCAL_PACKAGES:
                        imports.add(node.module)
            records.append(
                (
                    path.relative_to(root).as_posix(),
                    len(source.splitlines()),
                    sorted(imports),
                    [
                        node.name
                        for node in tree.body
                        if isinstance(node, (ast.FunctionDef, ast.ClassDef))
                    ],
                )
            )
    return records


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "docs" / "source_inventory.md")
    args = parser.parse_args()
    records = inspect_sources()
    lines = [
        "# Source inventory",
        "",
        "Generated by `python tools/audit_project.py`.",
        "",
        "Static imports and top-level symbols only; dynamic uses and external callers may exist.",
        "All listed files compile and parse with Python 3.10 syntax.",
        "",
        "| Source | Lines | Local imports | Top-level symbols |",
        "|---|---:|---|---|",
    ]
    for name, count, imports, symbols in records:
        lines.append(f"| `{name}` | {count} | {', '.join(imports)} | {', '.join(symbols)} |")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Compiled {len(records)} Python files; inventory: {args.output}")


if __name__ == "__main__":
    main()
